#!/usr/bin/env python3

import re

with open("src/season.js", "r+", encoding="utf-8") as file:
    content = file.read()

    if "return Animal.Rabbit" in content:
        content = re.sub("Animal.Rabbit", "Animal.Duck", content)
        SEASON = "Duck Season"
    else:
        content = re.sub("Animal.Duck", "Animal.Rabbit", content)
        SEASON = "Rabbit Season"

    file.seek(0)
    file.write(content)
    file.truncate()

print(f"::set-output name=season::{SEASON}")
