#!/usr/bin/env python3

import json
import subprocess
import sys

# what is current pr open for season switch
labels = ["rabbit", "duck"]

pr_label = None
for lbl in labels:
    command = f"gh pr list --label {lbl} --json number"
    process = subprocess.run(
        command, shell=True, check=True, stdout=subprocess.PIPE, universal_newlines=True
    )

    if process.returncode != 0:
        continue
    else:
        # Parse the output as JSON
        output = process.stdout
        data = json.loads(output)

        if data:
            pr = data[0]["number"]
            pr_label = lbl
            break

if pr_label is None:
    print("No PR found with label duck or rabbit")
    sys.exit(0)

# Merge the pull request
merge_command = f"gh pr merge {pr} --merge"
merge_process = subprocess.run(
    merge_command,
    shell=True,
    check=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    universal_newlines=True,
)

if merge_process.returncode == 0:
    print(f"Merged pull request number {pr}")
else:
    print(f"Failed to merge pull request number {pr}")
    print(f"Error: {merge_process.stderr}")
    sys.exit(1)
