#!/usr/bin/env python3

import argparse
import json
import os
import subprocess
import sys

# Create the parser
parser = argparse.ArgumentParser(
    description="Merge pull requests with a specific label."
)

# Add the arguments
parser.add_argument(
    "--pr-label",
    type=str,
    required=True,
    help="The label of the pull requests to merge.",
)

# Parse the arguments
args = parser.parse_args()

PR_LABEL = args.pr_label

command = f"gh pr list --label {PR_LABEL} --json number"
process = subprocess.run(
    command, shell=True, check=True, stdout=subprocess.PIPE, universal_newlines=True
)

if process.returncode != 0:
    print(f"Failed to get list of pull requests with label {PR_LABEL}")
    sys.exit(1)

# Parse the output as JSON
output = process.stdout
data = json.loads(output)

if data:
    pr = data[0]["number"]

    # Merge the pull request
    merge_command = f"gh pr merge {pr} --merge"
    merge_process = subprocess.run(
        merge_command,
        shell=True,
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )

    if merge_process.returncode == 0:
        print(f"Merged pull request number {pr}")
    else:
        print(f"Failed to merge pull request number {pr}")
        print(f"Error: {merge_process.stderr}")
        sys.exit(1)
else:
    print(f"No record found with label {PR_LABEL}")
