#!/usr/bin/env python3

import json
import os
import re
import subprocess

PR_LABEL = os.getenv("PR_LABEL")

command = f"gh pr list --label {PR_LABEL} --json number"
process = subprocess.run(
    command, shell=True, check=True, stdout=subprocess.PIPE, universal_newlines=True
)

if process.returncode != 0:
    print(f"Failed to get list of pull requests with label {PR_LABEL}")
    exit(1)

# Parse the output as JSON
output = process.stdout
data = json.loads(output)

if data:
    pr = data[0]["number"]

    # Merge the pull request
    merge_command = f"gh pr merge {pr} --merge"
    merge_process = subprocess.run(
        merge_command,
        shell=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        universal_newlines=True,
    )

    if merge_process.returncode == 0:
        print(f"Merged pull request number {pr}")
    else:
        print(f"Failed to merge pull request number {pr}")
        print(f"Error: {merge_process.stderr}")
else:
    print(f"No record found with label {PR_LABEL}")
