name: Python Tests

on:
  schedule:
    - cron: 0 */6 * * *
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description:
          The version of `analytics-cli` to use. Defaults to the latest specified in
          `analytis-uploader`.

jobs:
  test:
    runs-on: public-amd64-small

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest tests
        uses: ./.github/actions/analytics-uploader-wrapper
        with:
          token: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
          cli-version: ${{ inputs.cli-version }}
          junit-paths: "**/*_test.xml"
          run:
            pytest python/pytest/** --junitxml=python/results/pytest/pytest_test.xml -o
            junit_family=xunit1

      - name: Run robotframework tests
        uses: ./.github/actions/analytics-uploader-wrapper
        if: ${{ always() }}
        with:
          token: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
          cli-version: ${{ inputs.cli-version }}
          junit-paths: "**/*_test.xml"
          run:
            pabot --testlevelsplit --outputdir=python/results/robotframework --output=robot_test.xml
            python/robotframework/**
