#!/usr/bin/env python3

import re

with open("src/season.js", "r+") as file:
    content = file.read()

    if "return Animal.Rabbit" in content:
        print("Bugs - 'Duck Season'")
        content = re.sub("Animal.Rabbit", "Animal.Duck", content)
    else:
        print("Daffy - 'Rabbit Season'")
        content = re.sub("Animal.Duck", "Animal.Rabbit", content)

    file.seek(0)
    file.write(content)
    file.truncate()
