#!/bin/bash

if grep -q 'return Animal.Rabbit' src/season.js; then
	echo "Bugs - 'Duck Season'"
	sed -i'' 's/Animal.Rabbit/Animal.Duck/g' src/season.js
else
	echo "Daffy - 'Rabbit Season'"
	sed -i'' 's/Animal.Duck/Animal.Rabbit/g' src/season.js
fi
