name: Bazel Tests

permissions: read-all

on:
  schedule:
    - cron: "*/6 * * * *"
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      # trunk-ignore(checkov/CKV_GHA_7)
      cli-version:
        type: string
        required: false
        description:
          The version of `analytics-cli` to use. Defaults to the latest specified in
          `analytis-uploader`.

jobs:
  test:
    runs-on: public-amd64-small

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: run tests
        run: bazel test //bazel/gtest:hello_test
        continue-on-error: true

      - name: upload tests
        if: ${{ always() }}
        uses: ./.github/actions/analytics-uploader-wrapper
        with:
          token-staging: ${{ secrets.TRUNK_STAGING_ORG_API_TOKEN }}
          token-prod: ${{ secrets.TRUNK_PROD_ORG_API_TOKEN }}
          token-dev: ${{ secrets.TRUNK_DEV_ORG_API_TOKEN }}
          token-dev2: ${{ secrets.TRUNK_DEV2_ORG_API_TOKEN }}
          token-dev3: ${{ secrets.TRUNK_DEV3_ORG_API_TOKEN }}
          token-dev4: ${{ secrets.TRUNK_DEV4_ORG_API_TOKEN }}
          cli-version: ${{ inputs.cli-version }}
          junit-paths: bazel-testlogs/**/test.xml
